/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almacenumg;

/**
 *
 * @author kenyv
 */
public class Principal extends javax.swing.JFrame {

    //Se crea un nuevo objeto de la clase para cada ventana interna:
    VentanaAgregar v1;
    VentanaRetirar v2;
    ConsultaIn v3;
    public Principal() {
        initComponents();
        //Se agrega la instanciacion para cada ventana interna
        v1=new VentanaAgregar(); 
        v2=new VentanaRetirar();
        v3=new ConsultaIn();
        add(v1);
        add(v2);
        add(v3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Finalizar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuAg = new javax.swing.JMenuItem();
        MenuRet = new javax.swing.JMenuItem();
        MenuCon = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Archivo");

        Finalizar.setText("Salir");
        jMenu1.add(Finalizar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Inventario");

        MenuAg.setText("Agregar");
        MenuAg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAgActionPerformed(evt);
            }
        });
        jMenu2.add(MenuAg);

        MenuRet.setText("Retirar");
        MenuRet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRetActionPerformed(evt);
            }
        });
        jMenu2.add(MenuRet);

        MenuCon.setText("Consultar");
        MenuCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConActionPerformed(evt);
            }
        });
        jMenu2.add(MenuCon);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Compras");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ventas");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Clientes");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Facturacion");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuAgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAgActionPerformed
        //Hacemos visible solo esta ventana
        v1.setVisible(true); 
        //Se remueven las otras ventanas
        v2.setVisible(false);
        v3.setVisible(false);
    }//GEN-LAST:event_MenuAgActionPerformed

    private void MenuRetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRetActionPerformed
        v2.setVisible(true);
        v1.setVisible(false);
        v3.setVisible(false);
    }//GEN-LAST:event_MenuRetActionPerformed

    private void MenuConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConActionPerformed
        v3.setVisible(true);
        v1.setVisible(false);
        v2.setVisible(false);
    }//GEN-LAST:event_MenuConActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Finalizar;
    private javax.swing.JMenuItem MenuAg;
    private javax.swing.JMenuItem MenuCon;
    private javax.swing.JMenuItem MenuRet;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
